version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: xxxxxxx
  DOCKER_PASS:
    secure: yyyyyyy
install:
  - docker version

build_script:
  - cmd /C ver
  - docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8 cmd /C ver
  - docker build -t joycebabu/msb -m 2GB .

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push joycebabu/msb
